### ISSUE TITLE
Maximum allowed size of 10,000 lines.

### ISSUE THREAD

**Issue by tonkatommy** [Ninjin89/Types-to-Expansion-Market-Converter-UI#2]
Can't modify the Expansion types.. I'm getting a max 10,000 lines error??
I've just done a fresh install of Expansion Bundle and it seems they are putting the types directly into the db/types.xml file now. I assume this has just happened with 1.8.33 update?
![image](https://github.com/Ninjin89/Types-to-Expansion-Market-Converter-UI/assets/13126529/f992dc10-61a3-4ae6-bfdd-4320e46f6091)

**Comment by tonkatommy** [comment]
Also unable to open market files.
![image](https://github.com/Ninjin89/Types-to-Expansion-Market-Converter-UI/assets/13126529/0ccb466a-319c-4bd3-a5f1-915e8a5556d0)

**Comment by Ninjin89** [comment]
> Can't modify the Expansion types.. I'm getting a max 10,000 lines error?? I've just done a fresh install of Expansion Bundle and it seems they are putting the types directly into the db/types.xml file now. I assume this has just happened with 1.8.33 update? ![image](https://user-images.githubusercontent.com/13126529/285384199-f992dc10-61a3-4ae6-bfdd-4320e46f6091.png)

As of version 1.2.2 (see [release notes](https://github.com/Ninjin89/Types-to-Expansion-Market-Converter-UI/releases/tag/v1.2.2)), our Types-to-Expansion Market Converter has an implemented limitation regarding the size of files it can process. This measure was necessary due to the current technical constraints of the converter when handling larger files. 

This wil change as soon as i can fix it. You need to Split your Types.xml until then.





> Also unable to open market files. ![image](https://user-images.githubusercontent.com/13126529/285398586-0ccb466a-319c-4bd3-a5f1-915e8a5556d0.png)

THis was also already fixed, which Version of the Converter do you use? and how does your SellPrice look like in the File?

**Comment by Ninjin89** [comment]
> Also unable to open market files. ![image](https://private-user-images.githubusercontent.com/13126529/285398586-0ccb466a-319c-4bd3-a5f1-915e8a5556d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4Njc4MDAsIm5iZiI6MTcwMDg2NzUwMCwicGF0aCI6Ii8xMzEyNjUyOS8yODUzOTg1ODYtMGNjYjQ2NmEtMzE5Yy00YmQzLWE1ZjEtOTE1ZThhNTU1NmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI0VDIzMTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOGMxNTBiNWUxNTM5ZGE2NzQ4ZGEyODgzMWRhNjZiOTI2NTJkOTFiMjI4YzcxOTFkMTQ1NjAyMzNjOTc4MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lTI_CV57s4uA7QVGcYXYdz6ybwfb78OKQsWsL4NNPCE)

Fixed the issue now in the latest Release: [V1.2.5](https://github.com/Ninjin89/Types-to-Expansion-Market-Converter-UI/releases/tag/v1.2.5)

**Comment by tonkatommy** [comment]
Just tested.. Seems to open up files ok now.
