### ISSUE TITLE
exe not in the download

### ISSUE THREAD

**Issue by tommyz4** [Ninjin89/Types-to-Expansion-Market-Converter-UI#4]
Hello how do I get the exe file.

**Comment by Ninjin89** [comment]
Please do read the Informations on the repositorie.

https://github.com/Ninjin89/Types-to-Expansion-Market-Converter-UI/releases

**Comment by Ninjin89** [comment]
> Hello how do I get the exe file.

Please do read the Informations on the repositorie.

https://github.com/Ninjin89/Types-to-Expansion-Market-Converter-UI/releases
