### ISSUE TITLE
Quests files not recognised as quests

### ISSUE THREAD

**Issue by Freakyman403** [Ninjin89/Types-to-Expansion-Market-Converter-UI#5]
My Quests with custom naming is not recognised as actual Quests but any quest i insert with the starting name Quest Does work.
![image](https://github.com/Ninjin89/Types-to-Expansion-Market-Converter-UI/assets/6248310/92d98ccc-0952-4886-89a1-d751921a7dbc)
![image](https://github.com/Ninjin89/Types-to-Expansion-Market-Converter-UI/assets/6248310/436e12a0-0655-4442-8f5c-82306da7297b)

Objectives Work without issue even with custom naming.
![image](https://github.com/Ninjin89/Types-to-Expansion-Market-Converter-UI/assets/6248310/82c3d215-62ce-462e-867e-3ca15d126e5e)
![image](https://github.com/Ninjin89/Types-to-Expansion-Market-Converter-UI/assets/6248310/b1807dfa-a5d4-4a32-b7da-fb218144e8a7)

I know this is more of a personal issue, but i like to name my files in associating with another file.

**Comment by Ninjin89** [comment]
> My Quests with custom naming is not recognised as actual Quests but any quest i insert with the starting name Quest Does work. ![image](https://private-user-images.githubusercontent.com/6248310/337067991-92d98ccc-0952-4886-89a1-d751921a7dbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTM2ODEsIm5iZiI6MTcxNzY1MzM4MSwicGF0aCI6Ii82MjQ4MzEwLzMzNzA2Nzk5MS05MmQ5OGNjYy0wOTUyLTQ4ODYtODlhMS1kNzUxOTIxYTdkYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMDU1NjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQ4NjcyZWRkYjY1YTQ1ZmYxY2QyMmQ2NmE0ZmJiNzA3ZDFhZmEwMDk2ZWI3OGE2ZTkwMzE3ODc4MGNmNjE3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dsIfkCGc2NDmhG_KZNELZa1bLA8iu_5tEp1V5HW1dgE) ![image](https://private-user-images.githubusercontent.com/6248310/337068171-436e12a0-0655-4442-8f5c-82306da7297b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTM2ODEsIm5iZiI6MTcxNzY1MzM4MSwicGF0aCI6Ii82MjQ4MzEwLzMzNzA2ODE3MS00MzZlMTJhMC0wNjU1LTQ0NDItOGY1Yy04MjMwNmRhNzI5N2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMDU1NjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGZiYTkzZjZkMDIxYzcxNGI0MTNmMTcxNzdkZWVhOGYzMTg1ZmUzN2YzYjhiNGViOGEwMTgwYTkwNDAxMjI4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o90lDIFKW8AG5D_xTXe5bODpBwUOggruVN9kPOFvUJY)
> 
> Objectives Work without issue even with custom naming. ![image](https://private-user-images.githubusercontent.com/6248310/337068692-82c3d215-62ce-462e-867e-3ca15d126e5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTM2ODEsIm5iZiI6MTcxNzY1MzM4MSwicGF0aCI6Ii82MjQ4MzEwLzMzNzA2ODY5Mi04MmMzZDIxNS02MmNlLTQ2MmUtODY3ZS0zY2ExNWQxMjZlNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMDU1NjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2M5MjE2ZGJiMTk5ZTgyM2EzYWRjMDlhNGQ5MzUzYzMyZWRhYWMwMjc5ZDZjMDMyZjRjN2E4ZDAzZTYwMGM1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wFUPaqECx2crOtp23bXTR9mpu1_m-MT3SF1KKwumRys) ![image](https://private-user-images.githubusercontent.com/6248310/337068749-b1807dfa-a5d4-4a32-b7da-fb218144e8a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTM2ODEsIm5iZiI6MTcxNzY1MzM4MSwicGF0aCI6Ii82MjQ4MzEwLzMzNzA2ODc0OS1iMTgwN2RmYS1hNWQ0LTRhMzItYjdkYS1mYjIxODE0NGU4YTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMDU1NjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2EwYjViNmViMjljZmY0MDU4NjYyNjRhMjIwNmVjNGMzYzdkZGUzMGYzNTcwOTI3NDk0MmZkZDY5MGVjNTlhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2v3HGx7yo1bEeuHWP_yI4xicNTuB8eAhnGdxrcmtnq8)
> 
> I know this is more of a personal issue, but i like to name my files in associating with another file.

Hello, in the upcoming update, with AIPatrol being back, it should be possible to use custom quest names.

I will drop this update soon. If you want to be notified, join the Discord :)

**Comment by Freakyman403** [comment]
Awesome new update worked. i feel like this is worth closing once again good job.
